### ISSUE TITLE
The code of NMS

### ISSUE THREAD

**Issue by hellojialee** [dlunion/EasyOpenPose#2]
Hi! Thank you for your project! I have a doubt about the none-maximum suppression in:
https://github.com/dlunion/EasyOpenPose/blob/master/easyOpenPose.cpp#L449
I don't understand why computing a weighted coordinates (weighted by its confidence?) in a region of 7*7.
Looking forward to your help. Thank you!

**Comment by dlunion** [comment]
sub-pixel
